apiVersion: v1
kind: Pod
metadata:
  name: example-admission-webhook
  labels:
    app: admission-webhook
spec:
  containers:
  - name: admission
    image: "gcr.io/kubernetes-e2e-test-images/webhook:1.15"
    args: ["--tls-cert-file=/var/certs/cert.pem", "--tls-private-key-file=/var/certs/key.pem", "--alsologtostderr", "-v=1", "2>&1"]
    ports:
      - containerPort: 9443
    volumeMounts:
    - mountPath: "/var/certs"
      name: certs
      readOnly: true
  volumes:
  - name: certs
    secret:
      secretName: admission-webhook-tls-certs
